"use client"

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import Layout from '../../../components/Layout'
import { useAuthStore } from '../../../store/useAuthStore'
import { apiFetch } from '../../../lib/api'

function dt(v){ return v ? new Date(v).toLocaleString([], { dateStyle:'medium', timeStyle:'short' }) : '' }
function badge(s){ if(s==='COMPLETED') return 'bg-emerald-50 text-emerald-800 border-emerald-200'; if(s==='REPAIRING') return 'bg-blue-50 text-blue-800 border-blue-200'; if(s==='PARTIALLY_RETURNED') return 'bg-indigo-50 text-indigo-800 border-indigo-200'; return 'bg-amber-50 text-amber-800 border-amber-200' }
const empty={type:'RECEIVED',receivedQuantity:'',repairedQuantity:'',faultyQuantity:'',pendingQuantity:'',returnedQuantity:'',comment:'',mentionedUserIds:[]}

export default function HardwareDetail(){
 const {id}=useParams(); const token=useAuthStore(s=>s.accessToken)
 const [batch,setBatch]=useState(null),[users,setUsers]=useState([]),[form,setForm]=useState(empty),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){ if(!token)return; try{ setBatch(await apiFetch(`/api/hardware/${id}`,token)); setUsers(await apiFetch('/api/workspaces/employees',token)); setError('') }catch(e){ setError(e.message) } }
 useEffect(()=>{ load(); const t=setInterval(load,30000); return()=>clearInterval(t) },[token,id])
 async function submit(e){ e.preventDefault(); setBusy(true); try{ await apiFetch(`/api/hardware/${id}/updates`,token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); setForm(empty); await load() }catch(e){ setError(e.message) }finally{ setBusy(false) } }
 if(!batch) return <Layout><div className="mx-auto max-w-5xl rounded-3xl border border-slate-200 bg-white p-6 text-sm font-bold text-black">{error||'Loading hardware batch...'}</div></Layout>
 return <Layout><div className="mx-auto max-w-[1500px] space-y-4 text-black"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><Link href="/hardware" className="text-xs font-black uppercase tracking-wider text-black/45">← Hardware</Link><h1 className="mt-1 text-3xl font-black">{batch.batchNo}</h1><p className="text-sm font-semibold text-black/60">{batch.bankName||batch.ticket?.ticketNo||'POS hardware movement'}</p></div><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${badge(batch.status)}`}>{batch.status}</span></div></section>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}
 <div className="grid gap-4 xl:grid-cols-[1fr_420px]"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-black">Batch summary</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[['Total POS',batch.totalQuantity],['Received',batch.receivedQuantity],['Repaired',batch.repairedQuantity],['Faulty',batch.faultyQuantity],['Pending',batch.pendingQuantity],['Returned',batch.returnedQuantity],['Assigned to',batch.assignedTo?.name||batch.assignedTo?.email],['Ticket',batch.ticket?.ticketNo],['Created',dt(batch.createdAt)]].map(([k,v])=><div key={k} className="rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3"><div className="text-[10px] font-black uppercase text-black/40">{k}</div><div className="mt-1 text-sm font-black">{v??'—'}</div></div>)}</div>{batch.note&&<p className="mt-4 rounded-2xl border border-slate-100 bg-white p-4 text-sm font-semibold text-black/70">{batch.note}</p>}</section>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-black">POS serial and problem list</h2><div className="overflow-x-auto rounded-2xl border border-slate-100"><div className="min-w-[760px]"><div className="grid grid-cols-[70px_1fr_1fr_1fr_120px] gap-2 bg-slate-50 px-3 py-2 text-xs font-black uppercase text-black/45"><div>SL</div><div>Serial</div><div>Problem</div><div>Note</div><div>Status</div></div><div className="divide-y divide-slate-100">{(batch.items||[]).map((item,index)=><div key={item.id||index} className="grid grid-cols-[70px_1fr_1fr_1fr_120px] gap-2 px-3 py-2 text-sm font-bold"><div>{index+1}</div><div className="font-mono">{item.serialNumber}</div><div>{item.problem}</div><div className="text-black/60">{item.note||'—'}</div><div>{item.status||'PENDING'}</div></div>)}{!(batch.items||[]).length&&<div className="p-5 text-center text-sm font-bold text-black/45">No POS item details saved for this batch.</div>}</div></div></div></section>
 <form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-black">Post hardware update</h2><div className="space-y-3"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold"><option value="RECEIVED">Received confirmation</option><option value="REPAIR_UPDATE">Repair update</option><option value="RETURNED">Return to bank</option><option value="COMMENT">Comment</option></select><div className="grid grid-cols-2 gap-2"><input type="number" value={form.receivedQuantity} onChange={e=>setForm({...form,receivedQuantity:e.target.value})} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold" placeholder="Received"/><input type="number" value={form.repairedQuantity} onChange={e=>setForm({...form,repairedQuantity:e.target.value})} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold" placeholder="Repaired"/><input type="number" value={form.faultyQuantity} onChange={e=>setForm({...form,faultyQuantity:e.target.value})} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold" placeholder="Faulty"/><input type="number" value={form.pendingQuantity} onChange={e=>setForm({...form,pendingQuantity:e.target.value})} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold" placeholder="Pending"/><input type="number" value={form.returnedQuantity} onChange={e=>setForm({...form,returnedQuantity:e.target.value})} className="col-span-2 rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold" placeholder="Returned to bank"/></div><select multiple value={form.mentionedUserIds} onChange={e=>setForm({...form,mentionedUserIds:Array.from(e.target.selectedOptions).map(o=>o.value)})} className="h-28 w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold"><option value="">Mention users optional</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.email}</option>)}</select><textarea value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})} className="min-h-24 w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold" placeholder="Comment, e.g. 15 POS repaired and sent back to bank"/><button disabled={busy} className="w-full rounded-2xl bg-black px-5 py-3 text-sm font-black text-white">Submit update</button></div></form></div>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-black">Hardware timeline</h2><div className="space-y-3">{batch.updates?.map(u=><div key={u.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-sm font-black">{u.user?.name||u.user?.email}</div><div className="text-xs font-bold text-black/45">{dt(u.createdAt)}</div></div><div className="mt-1 text-xs font-black uppercase text-black/45">{u.type}</div><div className="mt-2 grid gap-2 text-xs font-bold text-black/60 sm:grid-cols-5">{[['Received',u.receivedQuantity],['Repaired',u.repairedQuantity],['Faulty',u.faultyQuantity],['Pending',u.pendingQuantity],['Returned',u.returnedQuantity]].map(([k,v])=><span key={k}>{k}: {v??'—'}</span>)}</div>{u.comment&&<p className="mt-2 text-sm font-semibold text-black/75">{u.comment}</p>}</div>)}</div></section></div></Layout>
}
