"use client"
import { useState } from 'react'
import { apiFetch } from '../../lib/api'
import { s, Icon, Field, downloadFile, Empty, label } from './shared'

const REPORTS = [['stock', 'Stock register', 'Every serial and its current position'], ['bank', 'Bank-wise stock', 'Availability and lifecycle by bank'], ['model', 'Model-wise stock', 'Device model and status totals'], ['deployment', 'Deployment', 'Merchant, engineer and TID / MID'], ['faulty', 'Faulty devices', 'Current faults awaiting service'], ['repair', 'Repair / RMA', 'Technicians, repair progress and costs'], ['replacement', 'Replacements', 'Linked serials and pending returns'], ['return', 'Withdrawals / returns', 'Withdrawal and previous return movements'], ['warranty', 'Warranty expiry', 'Expired and next 30 days by default'], ['movement', 'Stock movements', 'Full serial movement history'], ['audit', 'Audit history', 'Device, bank and access changes']]
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))
export default function Reports({ summary, token, onError }) {
  const [type, setType] = useState('stock')
  const [filters, setFilters] = useState({})
  const [preview, setPreview] = useState(null)
  const [busy, setBusy] = useState(false)
  const query = new URLSearchParams({ type, ...Object.fromEntries(Object.entries(filters).filter(([,v]) => v)) })
  const groupedServiceReport = ['faulty', 'repair'].includes(type)
  function serviceReportHtml(result) {
    const groups = new Map()
    result.rows.forEach(row => {
      const bank = row.Bank || 'Warehouse / unassigned'
      if (!groups.has(bank)) groups.set(bank, [])
      groups.get(bank).push(row)
    })
    const reportNumber = `NBL-RMA-${new Date(result.generatedAt).toISOString().slice(0, 10).replaceAll('-', '')}`
    const reportDate = new Date(result.generatedAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })
    return [...groups.entries()].map(([bank, rows]) => {
      const bankInfo = summary.banks.find(item => item.name === bank)
      const repaired = rows.filter(row => ['REPAIRED', 'Repaired', 'COMPLETED', 'Completed'].includes(row.Status) || ['REPAIRED', 'Repaired', 'COMPLETED', 'Completed'].includes(row.Repair)).length
      const pending = rows.length - repaired
      return `<section class="bank-section"><header class="report-header"><div class="brand"><h1>Networld Bangladesh PLC</h1><h2>REPAIR &amp; MAINTENANCE SERVICE REPORT</h2></div><div class="tagline">Reliable Technology<br>for a Stronger<br>Banking Tomorrow</div></header><div class="report-meta"><div><b>Report No:</b><strong>${escapeHtml(reportNumber)}</strong></div><div><b>Date:</b><strong>${escapeHtml(reportDate)}</strong></div><div><b>Bank:</b><strong>${escapeHtml(bank)}</strong></div><div><b>Total POS:</b><strong>${rows.length}</strong></div></div><table class="service-table"><thead><tr><th>SL</th><th>POS SERIAL</th><th>TID</th><th>LOCATION</th><th>FAULT</th><th>REPAIR RESULT</th><th>TECHNICIAN</th><th>REMARKS</th></tr></thead><tbody>${rows.map((row, index) => `<tr><td>${String(index + 1).padStart(2, '0')}</td><td>${escapeHtml(row.Serial || '')}</td><td>${escapeHtml(row.TID || '')}</td><td>${escapeHtml(row.Location || '')}</td><td>${escapeHtml(row.Fault || '')}</td><td>${escapeHtml(row.Repair || row.Status || '')}</td><td>${escapeHtml(row.Technician || '')}</td><td>${escapeHtml(row.Remarks || '')}</td></tr>`).join('')}</tbody></table><div class="summary"><b>Summary:</b><span>Repaired: <strong>${repaired}</strong></span><span>Pending: <strong>${pending}</strong></span><span>Total Cost: <strong>BDT ${rows.reduce((total, row) => total + (Number(row.RepairCost) || 0), 0).toFixed(2)}</strong></span></div><div class="signatures"><div><span></span><strong>Bank Representative</strong><small>Name / Signature / Date</small></div><div><span></span><strong>Networld Inventory Officer</strong><small>Name / Signature / Date</small></div><div><span></span><strong>Authorized Approver</strong><small>Name / Signature / Date</small></div></div></section>`
    }).join('') || '<p>No records match these filters.</p>'
  }
  async function run(format) {
    setBusy(true)
    let printWindow
    if (format === 'pdf') { printWindow = window.open('', '_blank'); if (!printWindow) { onError('Allow pop-ups to open the PDF print view.'); setBusy(false); return } printWindow.document.write('<title>Preparing report</title><p>Preparing report…</p>'); printWindow.document.close() }
    try {
      if (format === 'xlsx') await downloadFile(`/api/hardware/reports?${query}&format=xlsx`, token, `pos-${type}-${new Date().toISOString().slice(0,10)}.xlsx`)
      else {
        const result = await apiFetch(`/api/hardware/reports?${query}`, token)
        if (format === 'preview') setPreview(result)
        else {
          printWindow.document.open()
          const columns = Object.keys(result.rows[0] || {}).filter(key => key !== 'Details')
          const content = groupedServiceReport ? serviceReportHtml(result) : `<table><thead><tr>${columns.map(c => `<th>${escapeHtml(c)}</th>`).join('')}</tr></thead><tbody>${result.rows.map(row => `<tr>${columns.map(c => `<td>${escapeHtml(row[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>${!result.rows.length ? '<p>No records match these filters.</p>' : ''}`
          const reportTitle = type === 'repair' ? 'Repair / MA Report' : `POS ${label(type)} Report`
          printWindow.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(reportTitle)}</title><style>@page{size:A4 portrait;margin:8mm 9mm}*{box-sizing:border-box}body{font:10px Arial,sans-serif;color:#172b3a;margin:0}.bank-section{break-after:page;margin:0 0 8px}.bank-section:last-child{break-after:auto}.report-header{display:flex;justify-content:space-between;align-items:center;background:#0d3554;color:white;border-bottom:3px solid #2c8195;padding:14px 16px;margin-bottom:9px}.report-header h1{font-size:28px;letter-spacing:.2px;margin:0 0 5px}.report-header h2{font-size:14px;letter-spacing:.4px;margin:0;color:#d7edf2}.tagline{border-left:1px solid #8fb4bf;padding-left:14px;font-size:9px;line-height:1.4;color:#e4f1f3}.report-meta{display:grid;grid-template-columns:1.25fr 1.4fr 1.6fr .75fr;border:1px solid #d8e2e4;background:#f4f7f8;margin-bottom:10px}.report-meta div{padding:7px 9px;border-right:1px solid #d8e2e4}.report-meta div:last-child{border-right:0}.report-meta b,.report-meta strong{display:block}.report-meta b{font-size:9px;color:#526976;font-weight:normal;margin-bottom:3px}.report-meta strong{font-size:11px;color:#123c43}.service-table{border-collapse:collapse;width:100%;font-size:10px;table-layout:fixed}.service-table th,.service-table td{border:1px solid #d4dfe2;padding:7px 6px;vertical-align:middle;text-align:left;overflow-wrap:anywhere}.service-table th{background:#126579;color:white;font-size:9px;letter-spacing:.1px}.service-table th:nth-child(1){width:5%}.service-table th:nth-child(2){width:15%}.service-table th:nth-child(3){width:12%}.service-table th:nth-child(4){width:13%}.service-table th:nth-child(5){width:17%}.service-table th:nth-child(6){width:13%}.service-table th:nth-child(7){width:11%}.service-table th:nth-child(8){width:14%}.service-table tbody tr:nth-child(even){background:#eef2f3}.service-table thead{display:table-header-group}.service-table tr{break-inside:avoid}.summary{display:flex;gap:20px;align-items:center;background:#eef3f4;margin-top:10px;padding:9px;color:#123c43;font-size:10px}.summary b{margin-right:2px}.summary span{white-space:nowrap}.signatures{display:flex;justify-content:space-between;gap:24px;margin:34px 10px 0}.signatures div{width:30%;text-align:center}.signatures span{display:block;border-top:1px solid #172b3a;margin-bottom:7px}.signatures strong,.signatures small{display:block}.signatures strong{font-size:9px}.signatures small{font-size:9px;color:#526976;margin-top:3px}button{padding:9px 15px;margin:0 0 10px;background:#0f766e;color:white;border:0;border-radius:5px}@media print{button{display:none}}</style></head><body><button id="print">Print / Save as PDF</button>${content}</body></html>`)
          printWindow.document.close(); printWindow.document.getElementById('print').onclick = () => printWindow.print(); printWindow.focus()
        }
      }
    } catch (e) { printWindow?.close(); onError(e.message) } finally { setBusy(false) }
  }
  return <div className={s.stack}><div><h2 className={s.sectionTitle}>Reports & exports</h2><p className={s.sub}>Choose a report, narrow the results, then download Excel or save the print view as PDF.</p></div><div className={s.reportCards}>{REPORTS.map(([key, name, description]) => <button key={key} aria-pressed={type === key} className={`${s.reportCard} ${type === key ? s.selected : ''}`} onClick={() => { setType(key); setPreview(null) }}><Icon name={key === 'audit' || key === 'movement' ? 'clock' : 'chart'}/><strong>{name}</strong><span className={s.sub}>{description}</span></button>)}</div>
    <section className={s.panel}><div className={s.filterGrid} style={{ borderBottom: 0 }}>{[['bankId', 'Bank'], ['model', 'Model'], ['from', 'From date'], ['to', 'To date'], ['q', 'Serial / merchant / TID'], ['location', 'Location'], ['warranty', 'Warranty'], ['archived', 'Record set']].map(([key, title]) => <Field key={key} name={key} title={title} type={['from','to'].includes(key) ? 'date' : 'text'} value={filters[key]} onChange={e => { setFilters({ ...filters, [key]: e.target.value }); setPreview(null) }} options={key === 'bankId' ? summary.banks.map(b => ({ value: b.id, label: b.name })) : key === 'model' ? summary.models.map(m => ({ value: m, label: m })) : key === 'warranty' ? ['valid','expiring','expired','unknown'] : key === 'archived' ? [{value:'false',label:'Current devices'},{value:'true',label:'Archived devices'}] : undefined}/>)}</div><div className={s.footer}><span>Up to 10,000 records per export</span><div className={s.actions}><button className={s.button} disabled={busy} onClick={() => run('preview')}>{busy ? 'Preparing…' : 'Preview'}</button><button className={s.button} disabled={busy} onClick={() => run('pdf')}><Icon name="file" size={15}/>PDF / Print</button><button className={s.primary} disabled={busy} onClick={() => run('xlsx')}><Icon name="download" size={15}/>Excel</button></div></div></section>
    {preview && <section className={s.panel}><div className={s.panelHead}><h2>{label(type)} preview</h2><span className={s.small}>{preview.rows.length} records · showing first 100</span></div>{preview.rows.length ? <div className={s.tableScroll}><table className={s.table}><thead><tr>{Object.keys(preview.rows[0]).filter(k => k !== 'Details').map(k => <th key={k}>{k}</th>)}</tr></thead><tbody>{preview.rows.slice(0,100).map((row,i) => <tr key={i}>{Object.entries(row).filter(([k]) => k !== 'Details').map(([k,v]) => <td key={k}>{String(v)}</td>)}</tr>)}</tbody></table></div> : <Empty title="No matching records">Try a different date range or filter.</Empty>}</section>}
  </div>
}
